#cloud-config
users:
  - name: ubuntu 
    sudo: ALL=(ALL) NOPASSWD:ALL 
    groups: users, admin 
    home: /home/ubuntu 
    shell: /bin/bash 
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDX4k9SXjsyxqkaCAwdVOzo3+z70dVHIM4fTuYcGAgVovlS2w5iEThzr5LWAtN3pbzt9iWzzFoApH0WxK9LgSsZ83/W7l1s9n7Fq8kPjqpExvXLvjh+Nns4KM0PG+WvO9jrsrCL+mCsqbvnT6C5fIsYhaGl8805O6zF7QVzfcFDNFs4GtLfmsvnw4qgCX9UZ6SXRVjYGzMqNh1G3pPdBrSBpWWV8+Efib+rlp+4RTJNwBJVw062IumHZsMSrDsG9ZORmiXsmnUDtjRRXkuR4XnFXlsxnQmTCohG+lsuDlN0VkCQfcTMluhYiK5iGrfbQUN6KrFDOyU+cJo2v2iZGTGF
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD 
ssh_pwauth: false 
disable_root: false 
package_update: true 
packages:
  - curl 
  - wget 
  - mariadb-server  

runcmd:
   - sudo mysql -sfu root -e "GRANT ALL ON *.* TO 'admin'@'%' IDENTIFIED BY 'password' WITH GRANT OPTION;" 
   - sudo sed -i 's/127.0.0.1/0.0.0.0/g' /etc/mysql/mariadb.conf.d/50-server.cnf 
   - sudo systemctl restart mariadb.service 

final_message: "Database server setup completed." 
