#cloud-config
users:
  - name: ubuntu #Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL #sudo-Regeln für diesen Benutzer
    groups: users, admin # Die Gruppen indenen der User hinzugefügt wird
    home: /home/ubuntu # Homeverzeichnis
    shell: /bin/bash # Standart Konsole
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCJqxXnSuCSEzND9bhzUK8x2Bmwf+izomEX1tu8tGzcvfysu2GpNXx3NWTxbxBde2IqLiDhnZzsDno2hh2yXSRNxbExsa+Rv2R8RRXHkELX/jBz/7sKn5lSk5kE80Vi7tLAo1b4Mb2v6sWCFCjHWdL6SUfQFKQhRZtpNFnCswnNfXId8uNu4ICGbWmZnMaghgsw6+Ah/l6wj+JPpioUOdRL/Gt+Hu0GSpsAxgXFAInUefKgfl9W4FOK8q43OvWjDPJfMRh+YWamtzrZ5a7LirhbNsf8FQKyIEwWoCMCfFelIMYKBKLHmS8y3YseNPKzlHSCfX/ITyw80RCKwdQ9PRGF # öffentlicher SSH-Schlüssel zur Authentifizierung des Benutzers   
ssh_pwauth: false # Passwort Authentifizierung fürr SSH ist deaktiviert
disable_root: false # Root zugriff ist aktiviert
package_update: true # Pakete werden während der Einrichtung aktualisiert
packages:
  - curl # curl wird installiert
  - wget # wget wird installiert
