#cloud-config
users:
  - name: ubuntu #Benutzername
    sudo: ALL=(ALL) NOPASSWD:ALL #sudo-Regeln für diesen Benutzer
    groups: users, admin # Die Gruppen indenen der User hinzugefügt wird
    home: /home/ubuntu # Homeverzeichnis
    shell: /bin/bash # Standart Konsole
    ssh_authorized_keys:
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCJqxXnSuCSEzND9bhzUK8x2Bmwf+izomEX1tu8tGzcvfysu2GpNXx3NWTxbxBde2IqLiDhnZzsDno2hh2yXSRNxbExsa+Rv2R8RRXHkELX/jBz/7sKn5lSk5kE80Vi7tLAo1b4Mb2v6sWCFCjHWdL6SUfQFKQhRZtpNFnCswnNfXId8uNu4ICGbWmZnMaghgsw6+Ah/l6wj+JPpioUOdRL/Gt+Hu0GSpsAxgXFAInUefKgfl9W4FOK8q43OvWjDPJfMRh+YWamtzrZ5a7LirhbNsf8FQKyIEwWoCMCfFelIMYKBKLHmS8y3YseNPKzlHSCfX/ITyw80RCKwdQ9PRGF # öffentlicher SSH-Schlüssel zur Authentifizierung des Benutzers 
      - ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQC0WGP1EZykEtv5YGC9nMiPFW3U3DmZNzKFO5nEu6uozEHh4jLZzPNHSrfFTuQ2GnRDSt+XbOtTLdcj26+iPNiFoFha42aCIzYjt6V8Z+SQ9pzF4jPPzxwXfDdkEWylgoNnZ+4MG1lNFqa8aO7F62tX0Yj5khjC0Bs7Mb2cHLx1XZaxJV6qSaulDuBbLYe8QUZXkMc7wmob3PM0kflfolR3LE7LResIHWa4j4FL6r5cQmFlDU2BDPpKMFMGUfRSFiUtaWBNXFOWHQBC2+uKmuMPYP4vJC9sBgqMvPN/X2KyemqdMvdKXnCfrzadHuSSJYEzD64Cve5Zl9yVvY4AqyBD # öffentlicher Schlüssel NUY
ssh_pwauth: false # Passwort Authentifizierung fürr SSH ist deaktiviert
disable_root: false # Root zugriff ist aktiviert
package_update: true # Pakete werden während der Einrichtung aktualisiert
packages:
  - apache2  # Webserver Apache wird installiert
  - adminer  # Adminer wird hinzugefügt, um die Datenbank GUI zu nutzen
  - php #
  - php-mysqli #
  - libapache2-mod-php #

runcmd:
  - sudo a2enconf adminer  # Adminer-Konfiguration für Apache aktivieren
  - sudo systemctl restart apache2  # Apache neu starten, um Änderungen zu übernehmen

write_files:
  - path: /var/www/html/db.php  
    content: | # Datenbank-Verbindungsdatei
      <?php
      $servername = "54.90.24.100";  # IP-Adresse des MySQL-Servers
      $username = "admin";  # Benutzername für den MySQL-Zugriff
      $password = "password";  # Passwort für den MySQL-Zugriff
      $dbname = "mysql";  # Datenbank, mit der die Verbindung hergestellt wird 

      # Erstellt eine neue Verbindung zur MySQL-Datenbank
      $conn = new mysqli($servername, $username, $password, $dbname);
      
      # Überprüft, ob die Verbindung erfolgreich ist, andernfalls wird eine Fehlermeldung ausgegeben
      if($conn -> connect_error){
        die("Connection failed: " . $conn->connect_error); 
      }
      echo "Connected successfully"; 

      # SQL-Abfrage, um die Host- und Benutzerdaten der MySQL-Benutzer anzuzeigen
      $sql = "select Host, User from mysql.user;";
      $result = $conn->query($sql);  # Führt die Abfrage aus

      # Schleife, um die Ergebnisse der Abfrage anzuzeigen
      while($row = $result->fetch_assoc()){
        echo($row["Host"] . " / " . $row["User"] . "<br />");  # Gibt Host und Benutzer jedes Datensatzes aus
      }
      ?>

  - path: /var/www/html/info.php
    content: | # PHP-Info-Seite
      <?php
      phpinfo(); 
      ?>

final_message: "Web server setup completed."
